### ISSUE TITLE
change associated data to Data docking unit or Data dock

### ISSUE THREAD

**Issue by loumir** [ivoa-std/MANGO#16]
[Docking-unit-graph.pdf](https://github.com/ivoa-std/MANGO/files/4972338/Docking-unit-graph.pdf)

a mango instance is enriched by docked elements of type : 
web endpoint , Voservice or Vo_Model_Instance. 
a special case of model instance is another source , associated to the main mangoObject. 

VO_Model_Instance is a template class for any IVOA model instance .

**Comment by lmichel** [comment]
Done
