### ISSUE TITLE
Parameter: suggested alternative

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/MANGO#25]
I strongly suggest that the Parameter class be renamed.
The term is already used in VOTable and Provenance with different meanings.. and Mango has at least some overlap with each of those domains.

I'd like to suggest the term "Property", which is typically used to when talking about these entities (even in the dm-usecases descriptions).

**Comment by lmichel** [comment]
I agree, `Parameter` was not the better choice.
Let's go with `Property`
I'll close the issue once the change will be committed.

**Comment by loumir** [comment]
I agree and also prefer Property instead of Parameter.

**Comment by lmichel** [comment]
You can find datasets with several properties  having the same semantics/ucd, thus you cannot expect the model to be able to distinguish all properties in 100% of the cases. 
Mango offers 3 levels to qualify the property semantic: 
* ucd->semantic->description. 
We assume that this is sufficient for clients to get what to do. 
In addition to this and taking into account your example, MANGO gives a straight access to all of the coord system components (e.g. filter definitions) which allows the client to well identify all properties e.g. mag.

**Comment by lmichel** [comment]
done, renamed as Property
