### ISSUE TITLE
Parameter: description

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/MANGO#28]
I'm not sure if this issue belongs here, or in the workshop (or both).. it pertains to both modeling and the annotation.

Parameter.description: ivoa:string[1]

Model:
* first, is multiplicity 1 for an element which is often missing from serializations
* as I understand it, things like 'description' are not typically modeled elements.  They do not DEFINE the object being modeled, but are merely ancillary information which may or may not be present for the benefit of a human 'reader'.
    * that does not mean that implementations would not/should not have 'description' attributes which convey any text included in the serialization.  Just that whether or not this exists is a requirement on the application and has no consequence to the execution of a science thread.
* I realize this is a grey area, so am not pushing for removal, but think it is worth a conversation
    * notice that Measure and Coordinate types do not have 'description' attributes while their VOTable counterparts often do include some sort of description, however trivial (eg: from standard properties case; "Attribute managed by Saada".)

Annotation
* as a modeled element (Parameter.description) one would like to be able to annotate it directly as a COLUMN or CONSTANT, referencing the existing description of the corresponding FIELD or PARAM (or GROUP or TABLE).  However, in VOTable, DESCRIPTION is just an element of other types, and cannot have an ID to reference.

**Comment by lmichel** [comment]
> first, is multiplicity 1 for an element which is often missing from serializations 

This still has to be checked

> as I understand it,

right, the description just gives to the annoter the opportunity to say something more

> I realize this is a grey area, 

Mango descriptions provides it. Form a mamgo point of view, it is more logical to have descriptions in Properties (question of scope)

> Annotation

Right. My annotation system propose shorcut element (prefixed by SC_) for this sort of purpose though this specific case is not taken into consideration for now.
This feature has been required by Gilles

**Comment by mcdittmar** [comment]
So, this may be important in our discussion about the annotation syntax.
  * it's a capability that the Mapping proposal does not have.  You cannot
annotate content within the VOTable atom (description, array cells, etc.)
  * the trick may be in deciding if it should.  If the 'need' is based on
accessing VOTable content which can reasonably be considered modeled
content.
    (and description may not be the best example), then the
annotation should accommodate it.
  * the alternative being to say this is not a model concept, but address
it in the annotation.
    "Any object may have a description. If supported by the implementation,
the value is pulled from the VOTable DESCRIPTION sub-node of the associated
PARAM|FIELD|TABLE" (we don't annotate GROUPs I think).

Hmm.. I just read through the description of the SC_* elements, and don't
see how these help in annotating content within the VOTable atom.
The description looks like it consolidates a group of ATTRIBUTE nodes to
populate a full ivoa:Quantity with one annotation tag.
In the Mapping syntax, this is not necessary since LITERAL, CONSTANT and
COLUMN can populate the full Quantity.
I don't think the SC_* tag helps unless the description is independently
serialized in its own PARAM|FIELD, in which case it is referable and not a
problem.

I've added a note into the Wiki for your implementations
<https://github.com/ivoa/dm-usecases/wiki/mango>.

**Comment by lmichel** [comment]
This is a good point.

SC_FIELD could carry the DESCRIPTION but it is better to allow to get that description by a specific tag.
I like you proposal:

>    "Any object may have a description. If supported by the implementation,
> the value is pulled from the VOTable DESCRIPTION sub-node of the associated
> PARAM|FIELD|TABLE" (we don't annotate GROUPs I think).
> 
Another option would be to add a new Element to the syntax
<DESCRIPTION dmrole=description ref="col#4">
instead of
<ATTRIBUTE dmrole=description ref=???>

**Comment by Bonnarel** [comment]
Having "descriptions" attributes in the model is not dependent from the annotation mechanism in VOTable. Or should not. Any serialization should allow to retrieve description by the same kind of method
print (Model.get(mod:instance.description))
Provenance model also have "descriptions" attributes for activities and entities called "comments". This is a text explaining what the entity/activity is all about (not to be confused with ActivityDescription  which is a class gathering features shared by many activities)
