### ISSUE TITLE
Source and AssociatedData

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/MANGO#30]
I'm working a new example case where I'm annotating multiple models (which is not actually relevant to this ticket).
In that example I want to take CSC data with:
 * TABLE - containing Master Source records = mango:Source instances (one per Source)
 * TABLE - containing Detection records = mango:Source instances (one per Observation)

I'd then like to associate the Detections for each Master source record.
 * I'm not sure if this is a Provenance relation or AssociatedData, but for this exercise I am using AssociatedData
   * and VOModelInstance flavor 

The issue is that there is no singular model element to place at ModelInstance.  The Source class if for a single record.
If I have 7 detections for Source.id=12345, I'd technically need 7 AssociatedData nodes (1 per detection).  It' maybe be worth adding a Catalog class which contains a collection of Source.

**Comment by lmichel** [comment]
Both detections and Provenance are associatedData:
Below are the model paths for those 2 cases:
1.  detections: `Source -> associatedDataDock -> AssociatedMangoInstance`
2. Provenance: `Source -> associatedDataDock -> VOModelInstance`

You approach for the detections is OK (1.).

About the `catalog` container you are suggesting:

`associatedDataDock` is a `1-n` relation. Then there is no need to introduce a *catalogue* container. 
This has been confirmed by my little experience with *ModelInstanceInVot* that showed up that we don't need this `catalog` container:

- This container is represented by the `AssociatedMangoInstance` {COLLECTION}, which is easily populated with a table {JOIN}. 

However, I haven't very much exercised this feature, and I agree that we should look ahead at the relevance of such a grouping.

**Comment by mcdittmar** [comment]
Ah.. I missed that there was an "AssociatedMangoInstance" box.. this is essentially a Catalog object, but can only be in the 'associated' role.

  * I'll shift my annotation accordingly.

**Comment by mcdittmar** [comment]
> Ah.. I missed that there was an "AssociatedMangoInstance" box.. this is essentially a Catalog object, but can only be in the 'associated' role.

Ergh.. correction, I didn't quite understand.  AssociatedMangoInstance composes 1 Source record... so is NOT a Catalog equivalent.

What you are saying is that I should make an AssociatedData node of type AssociatedMangoInstance for each individual Detection(Source) record..  not quite what I was going for.

In the example I'm working with I will have:
  Source[id] with 2:7 AssociatedMangoInstance(Source) + 1 AssociatedModelInstance(SparseCube)

where I was looking to create:
  Source[id] with 1 AssociatedMangoInstance(Source[2:7]) + 1 AssociatedModelInstance(SparseCube)

where AssociatedMangoInstance(Source[2:7]) == Catalog of the previous message.

**Comment by lmichel** [comment]
You are right.
The fact that we have usually multiple detections for one source is not reflected here.
We should likely have a AssociatedMagoInstance**S** that have a 1-n association (namely mangoInstance**s**) with Source
