### ISSUE TITLE
VOModelInstance relation to ModelInstance

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/MANGO#32]
The current Mango model AssociatedData thread for including model instances (ModelInstance) uses a compositon relation.
I think this should be a reference relation.
* the Mango object does not own the associated object
* It is another form of referencing the target object
    * WebEndpoint: references by uri
    * VOModelInstance: references the embedded instance
* the description for VOModelInstance
    *   "**Reference** to a VO model instance that is part of the associated data."

**Comment by lmichel** [comment]
You are right
